#!/usr/bin/python3.8 



import os, sys

from Bio import SeqIO 
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

'''
Use outputs of MMseqs2 clustering to generate fasta files for each clusters + size statistics

Args 
    directory automatically generated by main.sh

'''

dir = sys.argv[1]
cov = sys.argv[2]


if not os.path.isdir(f"/home/simon.herman/Bureau/SCERs_pep/{dir}"):

    raise IsADirectoryError("Wrong directory, cannot change")

os.chdir(f"/home/simon.herman/Bureau/SCERs_pep/{dir}")

if not os.path.isdir("clusters"):
    os.mkdir("clusters")

reads = list(SeqIO.parse("clu_seq.fasta", format = "fasta"))

i = 0
buffer = []
sizes = []
for read in reads:

    if read.seq == "":

        cluster_size = len(buffer)

        if not os.path.isdir(f"clusters/size_{cluster_size}"):

            os.mkdir(f"clusters/size_{cluster_size}")
        
        handle = open(f"clusters/size_{cluster_size}/cluster_n{i}","w") 
        SeqIO.write(buffer, handle, format = "fasta")
        handle.close()

        buffer = []
        i = i+1
        
        handle = open(f"sizes{cov}.txt","a")
        handle.write(str(cluster_size)+"\n")
        handle.close()

    else:

        buffer.append(read)

# Last sequences still in buffer
cluster_size = len(buffer)

if not os.path.isdir(f"clusters/size_{cluster_size}"):

    os.mkdir(f"clusters/size_{cluster_size}")

handle = open(f"clusters/size_{cluster_size}/cluster_n{i}","w") 
SeqIO.write(buffer, handle, format = "fasta")
handle.close()
